---
title: 'Proposal EDA'
author: 'william Kawira (80533466)'
date: "11 March, 2025"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
library(ggplot2)
```

#Starbucks Plot

```{r, echo=TRUE, fig.height=4}
starbucks <- read.csv("Starbucks.csv")
head(starbucks)
starbucks$Date <- as.Date(starbucks$Date, format="%m/%d/%Y")
starbucks$Close.Last <- as.numeric(gsub("[$]", "", starbucks$Close.Last))
ggplot(starbucks, aes(x = Date, y = Close.Last)) +
  geom_line(color = "blue") +  
  labs(title = "Starbucks Stocks Closing Prices Over Time",
       x = "Date",
       y = "Closing Price") +
  theme_minimal()
```

#Kroger Plot

```{r, echo=TRUE, fig.height=4}
kroger <- read.csv("Kroger.csv")
head(kroger)
kroger$Date <- as.Date(kroger$Date, format="%m/%d/%Y")
kroger$Close.Last <- as.numeric(gsub("[$]", "", kroger$Close.Last))
ggplot(kroger, aes(x = Date, y = Close.Last)) +
  geom_line(color = "blue") +  
  labs(title = "Kroger Stocks Closing Prices Over Time",
       x = "Date",
       y = "Closing Price") +
  theme_minimal()
```

#SP500 Plot

```{r, echo=TRUE, fig.height=4}
sp500 <- read.csv("SP500.csv")
head(sp500)
sp500$Date <- as.Date(sp500$Date, format="%m/%d/%Y")
sp500$Close.Last <- as.numeric(sp500$Close.Last)
ggplot(sp500, aes(x = Date, y = Close.Last)) +
  geom_line(color = "blue") +  
  labs(title = "S&P 500 Closing Prices Over Time",
       x = "Date",
       y = "Closing Price") +
  theme_minimal()
```

#DXY Plot

```{r, echo=TRUE, fig.height=4}
dxy <- read.csv("DXY.csv")
head(dxy)
dxy$Date <- as.Date(dxy$Date, format="%m/%d/%Y")
dxy$Price <- as.numeric(dxy$Price)
ggplot(dxy, aes(x = Date, y = Price)) +
  geom_line(color = "blue") +  
  labs(title = "DXY Closing Prices Over Time",
       x = "Date",
       y = "Closing Price") +
  theme_minimal()
```
